#FROM ubuntu
#ADD jdk-8u74-linux-x64.tar.gz /opt/java
#ENV JAVA_HOME /opt/java/jdk1.8.0_74
#ENV PATH $PATH:$JAVA_HOME/bin
FROM java:8
EXPOSE 8080
#CMD nohup java -jar /home/app.jar &
CMD java -jar /home/app.jar

